# Fixed Group CRD with projects field
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: groups.identity.karectl.io
spec:
  group: identity.karectl.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                description:
                  type: string
                members:
                  type: array
                  items:
                    type: string
                subgroups:
                  type: array
                  items:
                    type: string
                projects:
                  type: array
                  items:
                    type: string
              required:
                - description
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          required:
            - spec
  scope: Namespaced
  names:
    plural: groups
    singular: group
    kind: Group
    shortNames:
      - grp
