apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakclients.identity.karectl.io
spec:
  group: identity.karectl.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clientId:
                  type: string
                name:
                  type: string
                secret:
                  type: string
                secretRef:
                  type: object
                  properties:
                    name:
                      type: string
                    key:
                      type: string
                      default: "client-secret"
                enabled:
                  type: boolean
                  default: true
                redirectUris:
                  type: array
                  items:
                    type: string
                webOrigins:
                  type: array
                  items:
                    type: string
                defaultClientScopes:
                  type: array
                  items:
                    type: string
                protocolMappers:
                  type: array
                  items:
                    type: object
                    additionalProperties: true
                additionalConfig:
                  type: object
                  additionalProperties: true
  scope: Namespaced
  names:
    plural: keycloakclients
    singular: keycloakclient
    kind: KeycloakClient
    shortNames:
      - kccli
