apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.identity.karectl.io
spec:
  group: identity.karectl.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                enabled:
                  type: boolean
                groups:
                  type: array
                  items:
                    type: string
                keycloak:
                  type: object
                  properties:
                    email_verified:
                      type: boolean
                jupyterhub:
                  type: object
                  properties:
                    workspace:
                      type: string
                    compute_quota:
                      type: string
                karectl:
                  type: object
                  properties:
                    user_id:
                      type: string
  scope: Namespaced
  names:
    plural: users
    singular: user
    kind: User
    shortNames:
      - usr
