apiVersion: apps/v1
kind: Deployment
metadata:
  name: cr8tor-operator
  labels:
    app: cr8tor-operator
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cr8tor-operator
  template:
    metadata:
      labels:
        app: cr8tor-operator
    spec:
      serviceAccountName: cr8tor-operator
      containers:
        - name: operator
          image: ghcr.io/karectl-crates/cr8tor-operator:v1.0.0
          imagePullPolicy: Always
          env:
            # Core operator configuration
            - name: LOG_LEVEL
              value: "INFO"
            - name: WORKER_LIMIT
              value: "5"
            - name: POSTING_ENABLED
              value: "false"
            - name: SERVER_TIMEOUT
              value: "60"
            - name: MANAGE_CRDS
              value: "true"
            - name: GENERATE_CRD_FILES
              value: "false"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-credentials
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-credentials
                  key: password
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: k8tre-realm-config
                  key: realm-name
            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: k8tre-realm-config
                  key: keycloak-url
            - name: KEYCLOAK_VERIFY_TLS
              valueFrom:
                configMapKeyRef:
                  name: k8tre-realm-config
                  key: keycloak-verify-tls

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
