name = "dataset_1"
description = "Metadata of required tables/columns"
schema_name = "z__cr8tor_poc"
[[tables]]
name = "concept"
[[tables.columns]]
name = "concept_class_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "concept_code"
description = ""
datatype = "STRING"


[staging_path]
file_path = "lsc/staging/data/outputs/database.duckdb"
"@id" = "301ecbce-528e-4cd9-999a-ae8279d153be"

[publish_path]
file_path = "lsc/production/data/outputs/database.duckdb"
hash_value = "f12190d5b8bd373103a6ecbd3e6f059d211c85fc3843888115c53f647c806afffdb2a55a6d98af4c78ecf5ee534d044a708240696a5852b484928ee10580f087"
total_bytes = 1585152
"@id" = "101db0ba-4200-41c7-9116-e958998d9e91"
