name = "default_name"
description = "Schema for cr8tor poc"
catalog = "rde_dev"
table_schema = "z__cr8tor_poc"
[[tables]]
name = "care_site"
description = ""
[[tables.columns]]
name = "care_site_id"
description = ""
datatype = "LONG"

[[tables.columns]]
name = "care_site_name"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "care_site_source_value"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "inserted_date_time"
description = ""
datatype = "TIMESTAMP"

[[tables.columns]]
name = "inserted_process_instance_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "inserted_process_queue_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "location_id"
description = ""
datatype = "LONG"

[[tables.columns]]
name = "place_of_service_concept_id"
description = ""
datatype = "LONG"

[[tables.columns]]
name = "place_of_service_source_value"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "source_system"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "updated_date_time"
description = ""
datatype = "TIMESTAMP"

[[tables.columns]]
name = "updated_process_instance_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "updated_process_queue_id"
description = ""
datatype = "STRING"


[[tables]]
name = "concept"
description = ""
[[tables.columns]]
name = "concept_class_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "concept_code"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "concept_id"
description = ""
datatype = "LONG"

[[tables.columns]]
name = "concept_name"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "domain_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "inserted_date_time"
description = ""
datatype = "TIMESTAMP"

[[tables.columns]]
name = "inserted_process_instance_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "inserted_process_queue_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "invalid_reason"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "source_system"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "standard_concept"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "updated_date_time"
description = ""
datatype = "TIMESTAMP"

[[tables.columns]]
name = "updated_process_instance_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "updated_process_queue_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "valid_end_date"
description = ""
datatype = "DATE"

[[tables.columns]]
name = "valid_start_date"
description = ""
datatype = "DATE"

[[tables.columns]]
name = "vocabulary_id"
description = ""
datatype = "STRING"


[[tables]]
name = "domain"
description = ""
[[tables.columns]]
name = "domain_concept_id"
description = ""
datatype = "LONG"

[[tables.columns]]
name = "domain_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "domain_name"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "inserted_date_time"
description = ""
datatype = "TIMESTAMP"

[[tables.columns]]
name = "inserted_process_instance_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "inserted_process_queue_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "source_system"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "updated_date_time"
description = ""
datatype = "TIMESTAMP"

[[tables.columns]]
name = "updated_process_instance_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "updated_process_queue_id"
description = ""
datatype = "STRING"


[[tables]]
name = "provider"
description = ""
[[tables.columns]]
name = "care_site_id"
description = ""
datatype = "LONG"

[[tables.columns]]
name = "dea"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "gender_concept_id"
description = ""
datatype = "LONG"

[[tables.columns]]
name = "gender_source_concept_id"
description = ""
datatype = "LONG"

[[tables.columns]]
name = "gender_source_value"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "inserted_date_time"
description = ""
datatype = "TIMESTAMP"

[[tables.columns]]
name = "inserted_process_instance_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "inserted_process_queue_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "npi"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "provider_id"
description = ""
datatype = "LONG"

[[tables.columns]]
name = "provider_name"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "provider_source_value"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "source_system"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "specialty_concept_id"
description = ""
datatype = "LONG"

[[tables.columns]]
name = "specialty_source_concept_id"
description = ""
datatype = "LONG"

[[tables.columns]]
name = "specialty_source_value"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "updated_date_time"
description = ""
datatype = "TIMESTAMP"

[[tables.columns]]
name = "updated_process_instance_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "updated_process_queue_id"
description = ""
datatype = "STRING"

[[tables.columns]]
name = "year_of_birth"
description = ""
datatype = "INT"


