project:
  name: "Test Project"
  description: "This is a test project"
  identifier: "test_project"

requesting_agent:
  name: "Prof. Jane Doe"
  affiliation: "Lancaster University"
  memberOf: ["Test Project"]

metadata_sources:
  - metadata/dataset_01.yaml
