project:
  name: "mph"
  description: "sadfsadf"
  identifier: "cr8-cr8-mph"

repository:
  name: "Github Repo"
  description: "This LSC-DIP RO-Crate is versioned and stored in a Git repository on GitHub."
  url: "https://github.com/lsc-sde-crates/"

requester:
  name: "Michael"
  affiliation:
    name: "e.g. jane.doe@someuni.com"
    url: "Lancs"

metadata_sources:
  - metadata/dataset_01.yaml
