apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-operator
  # namespace: keycloak  # Should be set by kustomization overlay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-operator
  template:
    metadata:
      labels:
        app: identity-operator
    spec:
      serviceAccountName: identity-operator
      containers:
        - name: operator
          image: ghcr.io/alwin-k-thomas/identity-operator:latest
          imagePullPolicy: Always
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-credentials
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-credentials
                  key: password
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: k8tre-realm-config
                  key: realm-name
            - name: KEYCLOAK_URL
              value: "http://keycloak.keycloak/"  # Should be overridden by environment
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KEYCLOAK_VERIFY_TLS
              value: "false"
            - name: LOG_LEVEL
              value: "INFO"