[source]
name = "Cr8tor PoC Connection"
type = "databrickssql"
host_url = "https://adb-1868816176859647.7.azuredatabricks.net"
port = 443
catalog = "rde_dev"
schema_name = "z__cr8tor_poc"
table = ["concept"]
http_path = "/sql/1.0/warehouses/0aec44b2e70e201d"

[credentials]
provider = "AzureKeyVault"
spn_clientid = "mph_test_clientid_key"
spn_secret = "mph_test_secret_key"
