apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakclients.identity.karectl.io
spec:
  group: identity.karectl.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              clientId:
                type: string
                description: Unique client identifier
              name:
                type: string
                description: Human-readable client name
              secret:
                type: string
                description: Client secret
              secretRef:
                type: object
                x-kubernetes-preserve-unknown-fields: true
                description: Reference to Kubernetes secret containing client secret
              enabled:
                type: boolean
                description: Whether the client is enabled
                default: true
              publicClient:
                type: boolean
                description: Whether this is a public client
                default: false
              redirectUris:
                type: array
                items:
                  type: string
              webOrigins:
                type: array
                items:
                  type: string
              protocol:
                type: string
                description: Authentication protocol
                default: openid-connect
              defaultClientScopes:
                type: array
                items:
                  type: string
              optionalClientScopes:
                type: array
                items:
                  type: string
              protocolMappers:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              attributes:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              additionalConfig:
                type: object
                x-kubernetes-preserve-unknown-fields: true
            required:
            - clientId
          status:
            type: object
            properties:
              phase:
                type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                  required:
                  - type
                  - status
                  - reason
                  - message
              observedGeneration:
                type: integer
            additionalProperties: true
        required:
        - spec
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: keycloakclients
    singular: keycloakclient
    kind: KeycloakClient
    shortNames:
    - key
