apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.research.karectl.io
spec:
  group: research.karectl.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              description:
                type: string
                description: Human-readable project description
              apps:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Application name
                    type:
                      type: string
                      description: Application type (e.g., jupyterhub, vdi)
                    url:
                      type: string
                      description: URL endpoint for the application
                    config:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                  required:
                  - name
                  - type
                  - url
                  additionalProperties: true
              profiles:
                type: array
                items:
                  type: object
                  properties:
                    display_name:
                      type: string
                      description: Human-readable profile name
                    description:
                      type: string
                      description: Profile description
                    slug:
                      type: string
                      description: URL-safe profile identifier
                    kubespawner_override:
                      type: object
                      properties:
                        image:
                          type: string
                          description: Container image for the profile
                        env:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                      additionalProperties: true
                      description: Kubespawner-specific overrides
                  required:
                  - display_name
                  - slug
                  additionalProperties: true
              resource_quota:
                type: object
                properties:
                  requests_cpu:
                    type: string
                    description: Total CPU requests allowed
                  requests_memory:
                    type: string
                    description: Total memory requests allowed
                  limits_cpu:
                    type: string
                    description: Total CPU limits allowed
                  limits_memory:
                    type: string
                    description: Total memory limits allowed
                  pods:
                    type: string
                    description: Maximum number of pods
                  services:
                    type: string
                    description: Maximum number of services
                  persistentvolumeclaims:
                    type: string
                    description: Maximum number of PVCs
                  requests_storage:
                    type: string
                    description: Total storage requests allowed
                additionalProperties: true
                description: Resource quota for the project namespace
              limit_range:
                type: object
                properties:
                  default_cpu:
                    type: string
                    description: Default CPU limit per container
                  default_memory:
                    type: string
                    description: Default memory limit per container
                  default_request_cpu:
                    type: string
                    description: Default CPU request per container
                  default_request_memory:
                    type: string
                    description: Default memory request per container
                additionalProperties: true
                description: Default limits for containers in the project namespace
              storage:
                type: object
                properties:
                  storage_class:
                    type: string
                    description: StorageClass to use for PVCs
                  default_vdi_size:
                    type: string
                    description: Default PVC size for VDI instances
                  default_notebook_size:
                    type: string
                    description: Default PVC size for Jupyter notebooks
                additionalProperties: true
                description: Storage configuration for the project
              scheduling:
                type: object
                properties:
                  node_selector:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  tolerations:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                          description: Toleration key
                        operator:
                          type: string
                          description: Operator (Equal or Exists)
                          default: Equal
                        value:
                          type: string
                          description: Toleration value
                        effect:
                          type: string
                          description: Effect (NoSchedule, PreferNoSchedule, NoExecute)
                        toleration_seconds:
                          type: integer
                          description: Toleration seconds for NoExecute
                      required:
                      - key
                      additionalProperties: true
                  affinity:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                    description: Pod affinity/anti-affinity rules
                  resources:
                    type: object
                    properties:
                      requests_cpu:
                        type: string
                        description: CPU request
                      requests_memory:
                        type: string
                        description: Memory request
                      limits_cpu:
                        type: string
                        description: CPU limit
                      limits_memory:
                        type: string
                        description: Memory limit
                    additionalProperties: true
                    description: Default resource requests/limits for workspaces
                  labels:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  annotations:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                additionalProperties: true
                description: Scheduling configuration for workspace pods
            required:
            - description
          status:
            type: object
            properties:
              phase:
                type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                  required:
                  - type
                  - status
                  - reason
                  - message
              observedGeneration:
                type: integer
            additionalProperties: true
        required:
        - spec
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: projects
    singular: project
    kind: Project
    shortNames:
    - pro
