apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.identity.karectl.io
spec:
  group: identity.karectl.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              username:
                type: string
                description: Unique username for the user
              email:
                type: string
                description: Email address of the user
              enabled:
                type: boolean
                description: Whether the user is enabled
                default: true
              password:
                type: string
                description: User password (if not set, a temporary password will
                  be generated)
              groups:
                type: array
                items:
                  type: string
              keycloak:
                type: object
                x-kubernetes-preserve-unknown-fields: true
                description: Keycloak-specific configuration
              jupyterhub:
                type: object
                x-kubernetes-preserve-unknown-fields: true
                description: JupyterHub-specific configuration
              karectl:
                type: object
                x-kubernetes-preserve-unknown-fields: true
                description: Karectl-specific configuration
            required:
            - username
            - email
          status:
            type: object
            properties:
              phase:
                type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                  required:
                  - type
                  - status
                  - reason
                  - message
              observedGeneration:
                type: integer
            additionalProperties: true
        required:
        - spec
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: users
    singular: user
    kind: User
    shortNames:
    - use
