apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vdiinstances.karectl.io
spec:
  group: karectl.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              user:
                type: string
              project:
                type: string
              image:
                type: string
              connection:
                type: string
              env:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    value:
                      type: string
                  required:
                  - name
                  - value
            required:
            - user
            - project
          status:
            type: object
            properties:
              phase:
                type: string
              password:
                type: string
  scope: Namespaced
  names:
    plural: vdiinstances
    singular: vdiinstance
    kind: VDIInstance