""" CRD registration are mapped by LinkML-generated models to k8s CRD metadata.

All Pydantic models are generated by cr8tor-metamodel
"""

from cr8tor.crd.registry import CRDRegistry

# Import all models from the LinkML generated module
from cr8tor_metamodel.datamodel.cr8tor_metamodel_pydantic import (
    # Governance
    User,
    # Deployment
    GroupSpec,
    KeycloakClientConfig,
    ProjectSpec,
    VDI,
)

# Register generated models with K8s CRD metadata
CRDRegistry.register("identity.k8tre.io", "v1alpha1", "User", "users")(User)
CRDRegistry.register("identity.k8tre.io", "v1alpha1", "KeycloakClient", "keycloakclients")(KeycloakClientConfig)
CRDRegistry.register("identity.k8tre.io", "v1alpha1", "Group", "groups")(GroupSpec)
CRDRegistry.register("research.k8tre.io", "v1alpha1", "Project", "projects")(ProjectSpec)
CRDRegistry.register("k8tre.io", "v1alpha1", "VDIInstance", "vdiinstances")(VDI)
