apiVersion: identity.karectl.io/v1alpha1
kind: Group
metadata:
  name: CR8TOR-001-admin
  labels:
    cr8tor.io/project-id: b0732f87-d663-4dd4-9ae9-780fd961c56d
    cr8tor.io/created-at: '20260212'
spec:
  description: CR8TOR-001 admin group
  attributes: {}
  members: []
  projects:
  - CR8TOR-001
  subgroups: []
