metadata_sources:
- metadata/dataset_01.yaml
project:
  '@id': proj-5b7e204a-37d3-4a63-9e35-423b05b1f226
  '@type': Project
  description: P002 created using CR8TOR.
  identifier: cr8-cr8-p002
  name: P002
repository:
  codeRepository: https://github.com/lsc-sde-crates/
  description: This LSC-DIP RO-Crate is versioned and stored in a Git repository on
    GitHub.
  name: Github Repo
requesting_agent:
  affiliation:
    name: Someuni
    url: https://someuni.com
  name: e.g. Prof. Jane Doe
