project:
  name: "Test Project"
  description: "This is a test project"
  identifier: "scsde-ref-1"

repository:
  name: "Github Repo"
  description: "This LSC-DIP RO-Crate is versioned and stored in a Git repository on GitHub."
  url: "https://github.com/lsc-sde-crates/"

requester:
  name: "Prof. Jane Doe"
  affiliation:
    name: "Lancaster University"
    url: "https://www.lancs.ac.uk"

metadata_sources:
  - metadata/dataset_01.yaml
