name: Init RO-Crate Project

on:
    workflow_call:
        inputs:
            governamce_yaml:
                description: path to user-defined governance inputs
                type: string
                required: true
            metadata_yaml:
                description: path to user-defined metadata inputs
                type: string
                required: true
        secrets:
            MPH_PAT_TOKEN:
                required: true
jobs:
  init-project:
    runs-on: ubuntu-latest
    env:
        ORG: lsc-sde-crates
        REPO_NAME: mph-test-project
        GH_TOKEN: ${{ secrets.MPH_PAT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Cr8tor Env
        run: |
          wget -qO- https://astral.sh/uv/install.sh | sh
          uv sync
          source .venv/bin/activate
          cd examples/simple_project
          cr8tor create

      - name: init repo
        run: |
          gh api -X DELETE "/repos/$ORG/$REPO_NAME"
          gh repo create "$ORG/$REPO_NAME" --private
      
      - name: Set id for git commit
        run: |
          git config --global user.name "LSCSDE Governance Action"
          git config --global user.email "lscsde-actions@github.com"

      - name: Push generated lscsde DAR project
        run: |
          mkdir generated-proj
          mv examples/simple_project/* generated-proj/
          cd generated-proj
          git init
          git remote add origin "https://$GH_TOKEN@github.com/$ORG/$REPO_NAME.git"
          git add .
          git commit -m "GA auto init and commit project"
          git branch -M main
          git push -u origin main
