name: Init RO-Crate Project

on:
    workflow_call:
        inputs:
            resources_target:
                description: path to user-defined project yaml
                type: string
                required: true
        secrets:
            MPH_PAT_TOKEN:
                required: true
jobs:
  init-project:
    runs-on: ubuntu-22.04
    env:
        ORG: lsc-sde-crates
        GH_TOKEN: ${{ secrets.MPH_PAT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Cr8tor Env
        run: |
          wget -qO- https://astral.sh/uv/install.sh | sh
          uv sync
          source .venv/bin/activate
          cd projects/${{ inputs.resources_target }}
          cr8tor create
      
      - name: Parse generated ro-crate metadata for project id
        run: |
          cd projects/${{ inputs.resources_target }}/bagit/data
          PROJ_UUID=$(jq -r '.["@graph"][] | select(."@type" == "Project")["@id"]' ro-crate-metadata.json)
          echo "REPO_NAME=$PROJ_UUID" >> $GITHUB_ENV

      - name: init repo
        run: |
          gh api -X DELETE "/repos/$ORG/$REPO_NAME"
          gh repo create "$ORG/$REPO_NAME" --private
      
      - name: Set id for git commit
        run: |
          git config --global user.name "LSCSDE Governance Actions"
          git config --global user.email "lscsde-actions@github.com"

      - name: Push generated lscsde DAR project
        run: |
          mkdir generated-proj
          mv projects/${{ inputs.resources_target }}/* generated-proj/
          cd generated-proj
          git init
          git remote add origin "https://$GH_TOKEN@github.com/$ORG/$REPO_NAME.git"
          git add .
          git commit -m "GA auto init and commit project"
          git branch -M main
          git push -u origin main
