name: Init RO-Crate Project

on:
  workflow_dispatch:
    inputs:
        new_project_name:
            description: Name of the new RO-Crate project
            type: string
            required: true
        environment:
          description: 'Target environment for the project'
          required: false
          default: 'PROD'
          type: choice
          options:
            - 'PROD'
            - 'DEV'
            - 'TEST'
        runner_os:
          description: 'Target runner OS for GitHub Actions workflows'
          required: false
          default: 'Windows'
          type: choice
          options:
            - 'Windows'
            - 'Linux'
        cr8tor_branch:
          description: 'CR8TOR branch to use'
          required: false
          default: 'main'
          type: string
        cookiecutter_branch:
          description: 'Cookiecutter template branch to use'
          required: false
          default: 'main'
          type: string

env:
    GH_TOKEN: ${{ secrets.ORG_LVL_RW_REPOS_TEAMS }}

jobs:
  init-project:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Run cr8tor Init
        run: |
          wget -qO- https://astral.sh/uv/install.sh | sh
          uv sync
          source .venv/bin/activate

          git config --global user.name "${{ github.repository_owner }} Governance Actions"
          git config --global user.email "${{ github.repository_owner }}-actions@github.com"

          ORG=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          cr8tor initiate -t https://github.com/${{ github.repository_owner }}/cr8-cookiecutter/ -chk "${{inputs.cookiecutter_branch}}" -cb "${{inputs.cr8tor_branch}}" -n "${{inputs.new_project_name}}" -org $ORG -e "${{inputs.environment}}" -ros "${{inputs.runner_os}}" --push
