name: Keep Runner Alive Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */240 * * *" # Runs every 10 days

jobs:
  Keep-Alive:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        runner: [dev-cr8tor-vm, test-cr8tor-vm, prod-cr8tor-vm]

    steps:
      - name: Print Message
        run: echo "Keeping Runner ${{ matrix.runner }} Alive"
